//! Proto ↔ Core type bidirectional conversion layer.
//!
//! The `ray.common` protobuf types are generated by `build.rs` and included
//! via the `proto` sub-module. This module provides conversion functions
//! between those proto types and the core Rust types defined in this crate.
//!
//! Server crates (ray-gcs, ray-raylet, ray-object-store) should use these
//! functions when translating gRPC requests/responses to/from core types.

use crate::error::{RayError, RayResult};
use crate::id;
use crate::resource::Resources;
use crate::traits;

// Include the generated protobuf code for `common.proto`.
#[allow(clippy::all)]
#[allow(unused_imports)]
pub mod proto {
    pub mod common {
        include!("ray.common.rs");
    }
}

// ──────────────────────────────────────────────
//  ID conversions
// ──────────────────────────────────────────────

macro_rules! impl_id_conv {
    ($core_ty:ty, $proto_ty:ty) => {
        impl From<$proto_ty> for $core_ty {
            fn from(p: $proto_ty) -> Self {
                <$core_ty>::from_vec(&p.id)
            }
        }

        impl From<$core_ty> for $proto_ty {
            fn from(c: $core_ty) -> Self {
                Self { id: c.to_vec() }
            }
        }
    };
}

impl_id_conv!(id::TaskId, proto::common::TaskId);
impl_id_conv!(id::ActorId, proto::common::ActorId);
impl_id_conv!(id::WorkerId, proto::common::WorkerId);
impl_id_conv!(id::ObjectId, proto::common::ObjectId);
impl_id_conv!(id::NodeId, proto::common::NodeId);
impl_id_conv!(id::JobId, proto::common::JobId);

/// Convert an `Option<ProtoId>` to a core ID, returning a default if `None`.
pub fn id_from_option<P, C>(opt: Option<P>) -> C
where
    P: Into<C>,
    C: Default,
{
    opt.map(Into::into).unwrap_or_default()
}

/// Convert a core ID to `Option<ProtoId>`.
pub fn id_to_option<C, P>(core_id: C) -> Option<P>
where
    C: Into<P>,
{
    Some(core_id.into())
}

// ──────────────────────────────────────────────
//  Resources conversions
// ──────────────────────────────────────────────

/// Convert a proto `Resources` to a core `Resources`.
pub fn resources_from_proto(p: &proto::common::Resources) -> Resources {
    let mut r = Resources::new();
    for (k, v) in &p.resource_map {
        r.map.insert(k.clone(), *v);
    }
    r
}

/// Convert an `Option<proto::Resources>` to a core `Resources` (empty if None).
pub fn resources_from_option(opt: Option<&proto::common::Resources>) -> Resources {
    opt.map(resources_from_proto).unwrap_or_default()
}

/// Convert a core `Resources` to a proto `Resources`.
pub fn resources_to_proto(r: &Resources) -> proto::common::Resources {
    proto::common::Resources {
        resource_map: r.map.clone(),
    }
}

/// Convert a core `Resources` to `Option<proto::Resources>`.
pub fn resources_to_option(r: &Resources) -> Option<proto::common::Resources> {
    Some(resources_to_proto(r))
}

// ──────────────────────────────────────────────
//  TaskSpec conversions
// ──────────────────────────────────────────────

/// Convert a proto `TaskSpec` to a core `TaskSpec`.
pub fn task_spec_from_proto(p: &proto::common::TaskSpec) -> RayResult<traits::TaskSpec> {
    let task_id = p
        .task_id
        .as_ref()
        .map(|t| id::TaskId::from(t.clone()))
        .ok_or_else(|| RayError::Internal("TaskSpec.task_id is required".to_string()))?;

    let job_id = p
        .job_id
        .as_ref()
        .map(|j| id::JobId::from(j.clone()))
        .ok_or_else(|| RayError::Internal("TaskSpec.job_id is required".to_string()))?;

    let return_ids = p.return_ids.iter().map(|o| id::ObjectId::from(o.clone())).collect();
    let dependency_ids = p
        .dependency_ids
        .iter()
        .map(|o| id::ObjectId::from(o.clone()))
        .collect();

    Ok(traits::TaskSpec {
        task_id,
        job_id,
        function_name: p.function_name.clone(),
        function_payload: p.function_payload.clone(),
        return_ids,
        dependency_ids,
        required_resources: resources_from_option(p.required_resources.as_ref()),
        max_retries: p.max_retries,
    })
}

/// Convert a core `TaskSpec` to a proto `TaskSpec`.
pub fn task_spec_to_proto(c: &traits::TaskSpec) -> proto::common::TaskSpec {
    proto::common::TaskSpec {
        task_id: id_to_option(c.task_id.clone()),
        job_id: id_to_option(c.job_id.clone()),
        function_name: c.function_name.clone(),
        function_payload: c.function_payload.clone(),
        return_ids: c.return_ids.iter().map(|o| o.clone().into()).collect(),
        dependency_ids: c.dependency_ids.iter().map(|o| o.clone().into()).collect(),
        required_resources: resources_to_option(&c.required_resources),
        caller_address: None,
        max_retries: c.max_retries,
        metadata: Default::default(),
    }
}

// ──────────────────────────────────────────────
//  ActorSpec conversions
// ──────────────────────────────────────────────

/// Convert a proto `ActorSpec` to a core `ActorSpec`.
pub fn actor_spec_from_proto(p: &proto::common::ActorSpec) -> RayResult<traits::ActorSpec> {
    let actor_id = p
        .actor_id
        .as_ref()
        .map(|a| id::ActorId::from(a.clone()))
        .ok_or_else(|| RayError::Internal("ActorSpec.actor_id is required".to_string()))?;

    let job_id = p
        .job_id
        .as_ref()
        .map(|j| id::JobId::from(j.clone()))
        .ok_or_else(|| RayError::Internal("ActorSpec.job_id is required".to_string()))?;

    Ok(traits::ActorSpec {
        actor_id,
        job_id,
        class_name: p.class_name.clone(),
        class_payload: p.class_payload.clone(),
        constructor_args: p.constructor_args.clone(),
        required_resources: resources_from_option(p.required_resources.as_ref()),
        max_restarts: p.max_restarts,
    })
}

/// Convert a core `ActorSpec` to a proto `ActorSpec`.
pub fn actor_spec_to_proto(c: &traits::ActorSpec) -> proto::common::ActorSpec {
    proto::common::ActorSpec {
        actor_id: id_to_option(c.actor_id.clone()),
        job_id: id_to_option(c.job_id.clone()),
        class_name: c.class_name.clone(),
        class_payload: c.class_payload.clone(),
        constructor_args: c.constructor_args.clone(),
        required_resources: resources_to_option(&c.required_resources),
        max_restarts: c.max_restarts,
        metadata: Default::default(),
    }
}

// ──────────────────────────────────────────────
//  TaskStatus conversions
// ──────────────────────────────────────────────

/// Convert a proto `TaskStatus` enum value (i32) to a core `TaskStatus`.
pub fn task_status_from_proto(v: i32) -> traits::TaskStatus {
    match proto::common::TaskStatus::try_from(v) {
        Ok(proto::common::TaskStatus::Pending) => traits::TaskStatus::Pending,
        Ok(proto::common::TaskStatus::Scheduled) => traits::TaskStatus::Scheduled,
        Ok(proto::common::TaskStatus::Running) => traits::TaskStatus::Running,
        Ok(proto::common::TaskStatus::Finished) => traits::TaskStatus::Finished,
        Ok(proto::common::TaskStatus::Failed) => traits::TaskStatus::Failed,
        Ok(proto::common::TaskStatus::Cancelled) => traits::TaskStatus::Cancelled,
        _ => traits::TaskStatus::Pending,
    }
}

/// Convert a core `TaskStatus` to a proto `TaskStatus` i32 value.
pub fn task_status_to_proto(s: traits::TaskStatus) -> i32 {
    match s {
        traits::TaskStatus::Pending => proto::common::TaskStatus::Pending as i32,
        traits::TaskStatus::Scheduled => proto::common::TaskStatus::Scheduled as i32,
        traits::TaskStatus::Running => proto::common::TaskStatus::Running as i32,
        traits::TaskStatus::Finished => proto::common::TaskStatus::Finished as i32,
        traits::TaskStatus::Failed => proto::common::TaskStatus::Failed as i32,
        traits::TaskStatus::Cancelled => proto::common::TaskStatus::Cancelled as i32,
    }
}

// ──────────────────────────────────────────────
//  ActorState conversions
// ──────────────────────────────────────────────

/// Convert a proto `ActorState` enum value (i32) to a core `ActorState`.
pub fn actor_state_from_proto(v: i32) -> traits::ActorState {
    match proto::common::ActorState::try_from(v) {
        Ok(proto::common::ActorState::Pending) => traits::ActorState::Pending,
        Ok(proto::common::ActorState::Alive) => traits::ActorState::Alive,
        Ok(proto::common::ActorState::Restarting) => traits::ActorState::Restarting,
        Ok(proto::common::ActorState::Dead) => traits::ActorState::Dead,
        _ => traits::ActorState::Pending,
    }
}

/// Convert a core `ActorState` to a proto `ActorState` i32 value.
pub fn actor_state_to_proto(s: traits::ActorState) -> i32 {
    match s {
        traits::ActorState::Pending => proto::common::ActorState::Pending as i32,
        traits::ActorState::Alive => proto::common::ActorState::Alive as i32,
        traits::ActorState::Restarting => proto::common::ActorState::Restarting as i32,
        traits::ActorState::Dead => proto::common::ActorState::Dead as i32,
    }
}

// ──────────────────────────────────────────────
//  NodeInfo conversions
// ──────────────────────────────────────────────

/// Convert core `NodeInfo` to fields suitable for building a proto GCS NodeInfo.
pub fn node_info_to_proto_fields(n: &traits::NodeInfo) -> NodeInfoProtoFields {
    NodeInfoProtoFields {
        node_id: id_to_option(n.node_id.clone()),
        address: n.address.clone(),
        port: n.port,
        total_resources: resources_to_option(&n.total_resources),
        available_resources: resources_to_option(&n.available_resources),
        is_alive: n.is_alive,
    }
}

/// Helper struct holding extracted proto fields for NodeInfo.
/// Server crates use these fields to construct their service-specific proto types.
pub struct NodeInfoProtoFields {
    pub node_id: Option<proto::common::NodeId>,
    pub address: String,
    pub port: i32,
    pub total_resources: Option<proto::common::Resources>,
    pub available_resources: Option<proto::common::Resources>,
    pub is_alive: bool,
}

// ──────────────────────────────────────────────
//  ActorInfo conversions
// ──────────────────────────────────────────────

/// Convert core `ActorInfo` to fields suitable for building a proto GCS ActorInfo.
pub fn actor_info_to_proto_fields(a: &traits::ActorInfo) -> ActorInfoProtoFields {
    ActorInfoProtoFields {
        actor_id: id_to_option(a.actor_id.clone()),
        job_id: id_to_option(a.job_id.clone()),
        class_name: a.class_name.clone(),
        state: actor_state_to_proto(a.state),
        node_id: id_to_option(a.node_id.clone()),
        num_restarts: a.num_restarts,
    }
}

/// Helper struct holding extracted proto fields for ActorInfo.
pub struct ActorInfoProtoFields {
    pub actor_id: Option<proto::common::ActorId>,
    pub job_id: Option<proto::common::JobId>,
    pub class_name: String,
    pub state: i32,
    pub node_id: Option<proto::common::NodeId>,
    pub num_restarts: i32,
}

// ──────────────────────────────────────────────
//  Unit tests
// ──────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_id_roundtrip_task_id() {
        let original = id::TaskId::new();
        let proto: proto::common::TaskId = original.clone().into();
        let restored: id::TaskId = proto.into();
        assert_eq!(original, restored);
    }

    #[test]
    fn test_id_roundtrip_object_id() {
        let original = id::ObjectId::new();
        let proto: proto::common::ObjectId = original.clone().into();
        let restored: id::ObjectId = proto.into();
        assert_eq!(original, restored);
    }

    #[test]
    fn test_id_roundtrip_node_id() {
        let original = id::NodeId::new();
        let proto: proto::common::NodeId = original.clone().into();
        let restored: id::NodeId = proto.into();
        assert_eq!(original, restored);
    }

    #[test]
    fn test_id_roundtrip_actor_id() {
        let original = id::ActorId::new();
        let proto: proto::common::ActorId = original.clone().into();
        let restored: id::ActorId = proto.into();
        assert_eq!(original, restored);
    }

    #[test]
    fn test_id_roundtrip_worker_id() {
        let original = id::WorkerId::new();
        let proto: proto::common::WorkerId = original.clone().into();
        let restored: id::WorkerId = proto.into();
        assert_eq!(original, restored);
    }

    #[test]
    fn test_id_roundtrip_job_id() {
        let original = id::JobId::new();
        let proto: proto::common::JobId = original.clone().into();
        let restored: id::JobId = proto.into();
        assert_eq!(original, restored);
    }

    #[test]
    fn test_id_from_option_none() {
        let result: id::TaskId = id_from_option(None::<proto::common::TaskId>);
        assert_eq!(result, id::TaskId::default());
    }

    #[test]
    fn test_id_from_option_some() {
        let original = id::TaskId::new();
        let proto = proto::common::TaskId { id: original.to_vec() };
        let result: id::TaskId = id_from_option(Some(proto));
        assert_eq!(result, original);
    }

    #[test]
    fn test_resources_roundtrip() {
        let original = Resources::new()
            .set("CPU", 4.0)
            .set("GPU", 2.0)
            .set("memory", 1024.0);
        let proto = resources_to_proto(&original);
        let restored = resources_from_proto(&proto);
        assert_eq!(original.get("CPU"), restored.get("CPU"));
        assert_eq!(original.get("GPU"), restored.get("GPU"));
        assert_eq!(original.get("memory"), restored.get("memory"));
    }

    #[test]
    fn test_resources_from_option_none() {
        let result = resources_from_option(None);
        assert!(result.map.is_empty());
    }

    #[test]
    fn test_task_spec_roundtrip() {
        let original = traits::TaskSpec {
            task_id: id::TaskId::new(),
            job_id: id::JobId::new(),
            function_name: "my_func".to_string(),
            function_payload: vec![1, 2, 3, 4],
            return_ids: vec![id::ObjectId::new()],
            dependency_ids: vec![id::ObjectId::new(), id::ObjectId::new()],
            required_resources: Resources::new().set("CPU", 2.0),
            max_retries: 3,
        };

        let proto = task_spec_to_proto(&original);
        let restored = task_spec_from_proto(&proto).unwrap();

        assert_eq!(original.task_id, restored.task_id);
        assert_eq!(original.job_id, restored.job_id);
        assert_eq!(original.function_name, restored.function_name);
        assert_eq!(original.function_payload, restored.function_payload);
        assert_eq!(original.return_ids.len(), restored.return_ids.len());
        assert_eq!(original.dependency_ids.len(), restored.dependency_ids.len());
        assert_eq!(
            original.required_resources.get("CPU"),
            restored.required_resources.get("CPU")
        );
        assert_eq!(original.max_retries, restored.max_retries);
    }

    #[test]
    fn test_actor_spec_roundtrip() {
        let original = traits::ActorSpec {
            actor_id: id::ActorId::new(),
            job_id: id::JobId::new(),
            class_name: "MyActor".to_string(),
            class_payload: vec![10, 20],
            constructor_args: vec![30, 40],
            required_resources: Resources::new().set("CPU", 1.0).set("GPU", 1.0),
            max_restarts: 5,
        };

        let proto = actor_spec_to_proto(&original);
        let restored = actor_spec_from_proto(&proto).unwrap();

        assert_eq!(original.actor_id, restored.actor_id);
        assert_eq!(original.job_id, restored.job_id);
        assert_eq!(original.class_name, restored.class_name);
        assert_eq!(original.class_payload, restored.class_payload);
        assert_eq!(original.constructor_args, restored.constructor_args);
        assert_eq!(original.max_restarts, restored.max_restarts);
    }

    #[test]
    fn test_task_status_roundtrip() {
        let statuses = [
            traits::TaskStatus::Pending,
            traits::TaskStatus::Scheduled,
            traits::TaskStatus::Running,
            traits::TaskStatus::Finished,
            traits::TaskStatus::Failed,
            traits::TaskStatus::Cancelled,
        ];
        for &s in &statuses {
            let proto_val = task_status_to_proto(s);
            let restored = task_status_from_proto(proto_val);
            assert_eq!(s, restored);
        }
    }

    #[test]
    fn test_actor_state_roundtrip() {
        let states = [
            traits::ActorState::Pending,
            traits::ActorState::Alive,
            traits::ActorState::Restarting,
            traits::ActorState::Dead,
        ];
        for &s in &states {
            let proto_val = actor_state_to_proto(s);
            let restored = actor_state_from_proto(proto_val);
            assert_eq!(s, restored);
        }
    }

    #[test]
    fn test_task_status_unspecified_defaults_to_pending() {
        let restored = task_status_from_proto(0); // Unspecified
        assert_eq!(restored, traits::TaskStatus::Pending);
    }

    #[test]
    fn test_actor_state_unspecified_defaults_to_pending() {
        let restored = actor_state_from_proto(0); // Unspecified
        assert_eq!(restored, traits::ActorState::Pending);
    }
}
